# Generated by Django 4.2.8 on 2024-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='İşler')),
                ('text', models.TextField()),
                ('date_now', models.DateTimeField(verbose_name='Tarih - Saat')),
            ],
        ),
    ]
