# Generated by Django 4.2.8 on 2024-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='İşler')),
                ('text', models.TextField()),
                ('date_now', models.DateTimeField(verbose_name='Tarih - Saat')),
                ('author', models.CharField(max_length=50, verbose_name='Yazar')),
            ],
        ),
        migrations.DeleteModel(
            name='Isler',
        ),
    ]
