# Generated by Django 4.2.8 on 2024-01-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_blog_delete_isler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='İletişim Yazısı')),
                ('img', models.FileField(upload_to='', verbose_name='CVLER')),
            ],
        ),
    ]
